name: Build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14', '3.14t']
    name: Test Python bindings using ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v6
      - name: Install system build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            linux-modules-extra-$(uname -r) \
            autoconf \
            autoconf-archive \
            automake \
            libtool \
            pkg-config \
            libkmod-dev \
            libmount-dev \
            libglib2.0-dev
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          pip install -U pip build setuptools
      - name: Configure build
        run: |
          ./autogen.sh --enable-bindings-python --enable-tests
      - name: Build library
        run: |
          make -j$(nproc)
      - name: Build python test suite
        run: |
          cd bindings/python
          make -j$(nproc) python-tests
      - name: Run python test suite
        run: |
          cd bindings/python
          sudo make python-tests-run